### ISSUE TITLE
Can't Play Previous Songs in Randon or Repeat Mode

### ISSUE THREAD

**Issue by jdh313** [mopidy/mopidy#1589] opened 2017-01-07 03:29 UTC
Using NCMPCPP controls or MPC Prev just result in the current song being repeated, it won't play the previous song.  This works find with MPD, however, eliminating it from being a client error.

I can provide any files you may need.

**Comment by kingosticks** [comment] 2017-01-07 12:34
Please provide your version of Mopidy and your version of mpd. 

We aim to emulate mpd and this is defined at https://docs.mopidy.com/en/latest/modules/mpd/#mopidy.mpd.protocol.playback.previous

It could well be that mpd's behaviour has changed since 0.15.4-1ubuntu3.

**Comment by jdh313** [comment] 2017-01-08 05:41
That could be it, I'm running MPD version 0.20, and Mopidy 2.1.0.

Now, I haven't been using either long (a couple months), so it very well could be that MPD changed their functionality recently and I saw that as the norm.  In all honesty, I'm just relieved that it's not an issue with my setup.  I can close this if you'd like.

**Comment by kingosticks** [comment] 2017-01-08 08:20
No, this is good to know and we probably do want to follow the latest mpd.

**Comment by jdh313** [comment] 2017-01-08 08:25
Thank you.

**Comment by jcass77** [comment] 2017-01-20 14:30
This seems to be a duplicate of #493.

**Comment by jodal** [comment] 2017-02-11 12:52
I added a note to #493 so we'll tackle these issues together. Closing this issue.

**Closed by jodal** 2017-02-11 12:52 UTC
Labels: Bug, Core
