### ISSUE TITLE
Local scan hanging on albumwrap file with .mp3 file extension

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy#797] opened 2014-07-26 15:31 UTC
@MrTango reported this issue on IRC some time ago, and we continued debugging it at the EuroPython sprint.

While trying to scan a 105MB large `.mp3` file (provided to @adamcik and @jodal through Dropbox) `mopidy local scan` hangs indefinitely, and Ctrl+C is not enough to stop it.

`GST_DEBUG=3 mopidy -v local scan` didn't tell me anything obvious.

`gst-launch-0.10 -t playbin2 uri=file:///home/.../x.mp3` managed to print the extracted metadata, but not to play any audio.

`mp3val` indicated some initial garbage and 13 MP3 streams:

```
$ mp3val ~/Music/x.mp3 
Analyzing file "x.mp3"...
WARNING: "/home/jodal/Music/x.mp3" (offset 0x0): Garbage at the beginning of the file
WARNING: "/home/jodal/Music/x.mp3" (offset 0x6f0635): MPEG stream error, resynchronized successfully
WARNING: "/home/jodal/Music/x.mp3" (offset 0x10bede4): MPEG stream error, resynchronized successfully
WARNING: "/home/jodal/Music/x.mp3" (offset 0x10c1aeb): MPEG stream error, resynchronized successfully
WARNING: "/home/jodal/Music/x.mp3" (offset 0x1825490): MPEG stream error, resynchronized successfully
WARNING: "/home/jodal/Music/x.mp3" (offset 0x1f2a3eb): MPEG stream error, resynchronized successfully
WARNING: "/home/jodal/Music/x.mp3" (offset 0x28e8e8a): MPEG stream error, resynchronized successfully
WARNING: "/home/jodal/Music/x.mp3" (offset 0x2fdb3f0): MPEG stream error, resynchronized successfully
WARNING: "/home/jodal/Music/x.mp3" (offset 0x379dbf3): MPEG stream error, resynchronized successfully
WARNING: "/home/jodal/Music/x.mp3" (offset 0x3d5a22a): MPEG stream error, resynchronized successfully
WARNING: "/home/jodal/Music/x.mp3" (offset 0x4565571): MPEG stream error, resynchronized successfully
WARNING: "/home/jodal/Music/x.mp3" (offset 0x4d675c7): MPEG stream error, resynchronized successfully
WARNING: "/home/jodal/Music/x.mp3" (offset 0x54da866): MPEG stream error, resynchronized successfully
WARNING: "/home/jodal/Music/x.mp3" (offset 0x5cd9feb): MPEG stream error, resynchronized successfully
INFO: "/home/jodal/Music/x.mp3": 102970 MPEG frames (MPEG 1 Layer III), +ID3v1, CBR
Done!
```

`xxd` shows us that the garbage is an "albumwrap" header:

```
$ xxd ~/Music/x.mp3 | head
0000000: 6275 6d54 414c 4200 0000 2a00 0000 416c  bumTALB...*...Al
0000010: 6275 6d57 7261 7020 2d20 5175 6565 6e20  bumWrap - Queen 
0000020: 2d20 4a61 7a7a 2028 5772 6170 2062 7920  - Jazz (Wrap by 
0000030: 524b 5237 3631 2954 5045 3100 0000 1200  RKR761)TPE1.....
0000040: 0000 416c 6275 6d57 7261 7020 2d20 5175  ..AlbumWrap - Qu
0000050: 6565 6e43 4f4d 4d00 0000 1d00 0000 416c  eenCOMM.......Al
0000060: 6275 6d57 7261 7020 2d20 524b 5237 3631  bumWrap - RKR761
0000070: 5b5d 5b5d 3637 302e 3933 0000 0000 0000  [][]670.93......
0000080: 0000 0000 0000 0000 0000 0000 0000 0000  ................
0000090: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```

So, this is obviously not a valid MP3 file, and I don't care much about being able to scan it properly. But, we should be able to scan and ignore the file without hanging.

**Comment by adamcik** [comment] 2015-04-10 22:17
Turns out the issue I mentioned in #726 is the same as this, and that I've rediscovered what I already wrote in the previous comment from scratch... This time around, I'm actually looking at doing the workaround...

**Comment by adamcik** [comment] 2015-04-10 22:19
Though, I'm not quite sure how much it helps fixing it in the scanner if Mopidy itself still chokes on it :/

**Comment by adamcik** [comment] 2016-02-15 20:49
Closing as we have a GStreamer 1.x version of Mopidy being released any minute now. Reopen if you can reproduce with this version.

**Closed by adamcik** 2016-02-15 20:49 UTC
Labels: Audio, bug
