### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by MrDini123** [mopidy/mopidy#1515] opened 2016-05-20 20:12 UTC
Hello!

Please add the Python3.5 supporting to the code, because I have some other python packages which only works with python3. Or if I simply uncomment this error message in the file, it will works?

Thanks a lot!

**Comment by adamcik** [comment] 2016-05-20 20:17
Duplicate of #779 - closing and yes we are slowly but surely moving in that direction now that we have our GStreamer 1.x migration done.

**Closed by adamcik** 2016-05-20 20:17 UTC

**Comment by adamcik** [comment] 2016-05-20 20:38
And to answer your question about un-commenting the check, feel free to try. But I don't think we are there yet. And I suspect a bunch of our extensions and their deps might not be ready yet for 2+3 which we plan to move to as a migration step.

**Comment by MrDini123** [comment] 2016-05-20 20:40
Ok, thanks!

And how many time (just about) when You finish the "upgrade"?

**Comment by jodal** [comment] 2016-05-20 21:33
This is open source, thus time estimates are mostly lies and bloody lies, so I'm not giving one.
