### ISSUE TITLE
Mopidy Core crashes when playing bbc podcast

### ISSUE THREAD

**Issue by AnsgarSchmidt** [mopidy/mopidy#1366] opened 2015-12-22 19:39 UTC
Hi, 

I am using mopidy 1.1.1.1 with odroid. When I try to play the bbc podcasts the mopidy core
crashes. 

Here is one example mp3 file
http://open.live.bbc.co.uk/mediaselector/5/redir/version/2.0/mediaset/audio-nondrm-download/proto/http/vpid/p02r4wlz.mp3
http://open.live.bbc.co.uk/mediaselector/5/redir/version/2.0/mediaset/audio-nondrm-download/proto/http/vpid/p02r5219.mp3

From this podcast:
http://downloads.bbc.co.uk/podcasts/radio4/myshakespeare/rss.xml

```
odroid@hal:/var/log/mopidy$ apt-cache policy mopidy
mopidy:
  Installed: 1.1.1-1
  Candidate: 1.1.1-1
  Version table:
 *** 1.1.1-1 0
        500 http://apt.mopidy.com/ stable/main armhf Packages
        100 /var/lib/dpkg/status
```

```
2015-12-22 12:51:56,409 INFO [17556:StreamBackend-6] urllib3.connectionpool: Starting new HTTP connection (1): open.live.bbc.co.uk
2015-12-22 12:51:56,555 ERROR [17556:Core-11] pykka: Unhandled exception in Core (urn:uuid:42489c57-2c26-44dc-b6b0-6050a0645de4):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy/listener.py", line 54, in on_event
    getattr(self, event)(**kwargs)
  File "/usr/lib/python2.7/dist-packages/mopidy/core/actor.py", line 87, in reached_end_of_stream
    self.playback._on_end_of_track()
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playback.py", line 232, in _on_end_of_track
    self._change_track(next_tl_track)
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playback.py", line 208, in _change_track
    self._play(on_error_step=on_error_step)
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playback.py", line 348, in _play
    backend.playback.change_track(tl_track.track).get() and
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy/backend.py", line 245, in change_track
    uri = self.translate_uri(track.uri)
  File "/usr/lib/python2.7/dist-packages/mopidy/stream/actor.py", line 88, in translate_uri
    requests_session=self._session)
  File "/usr/lib/python2.7/dist-packages/mopidy/stream/actor.py", line 140, in _unwrap_stream
    requests_session, uri, timeout=download_timeout)
  File "/usr/lib/python2.7/dist-packages/mopidy/internal/http.py", line 26, in download
    response = session.get(uri, stream=True, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 578, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 165, in resolve_redirects
    proxies = self.rebuild_proxies(prepared_request, proxies)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 239, in rebuild_proxies
    username, password = get_auth_from_url(new_proxies[scheme])
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 642, in get_auth_from_url
    parsed = urlparse(url)
  File "/usr/lib/python2.7/urlparse.py", line 143, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python2.7/urlparse.py", line 182, in urlsplit
    i = url.find(':')
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by ernesst** [comment] 2016-01-03 13:12
Hello, 
On my side i got this while playing google music, I don't know if it's related.


2016-01-03 12:54:18,930 ERROR [1242:Core-15] pykka: Unhandled exception in Core (urn:uuid:bb515176-d34f-44ba-9c95-9aeeb91fa034):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy/listener.py", line 54, in on_event
    getattr(self, event)(**kwargs)
  File "/usr/lib/python2.7/dist-packages/mopidy/core/actor.py", line 87, in reached_end_of_stream
    self.playback._on_end_of_track()
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playback.py", line 232, in _on_end_of_track
    self._change_track(next_tl_track)
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playback.py", line 208, in _change_track
    self._play(on_error_step=on_error_step)
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playback.py", line 348, in _play
    backend.playback.change_track(tl_track.track).get() and
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy/backend.py", line 245, in change_track
    uri = self.translate_uri(track.uri)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/playback.py", line 24, in translate_uri
    track_id, quality=quality)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/session.py", line 31, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/session.py", line 78, in get_stream_url
    return self.api.get_stream_url(song_id, quality=quality)
  File "<decorator-gen-78>", line 2, in get_stream_url
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 290, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 271, in get_stream_url
    return self._make_call(mobileclient.GetStreamUrl, song_id, device_id, quality)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 81, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 208, in perform
    response = session.send(req_kwargs, cls.required_auth)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 87, in send
    res = self._send_with_auth(req_kwargs, desired_auth, rsession)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 196, in _send_with_auth
    return rsession.request(**req_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 331, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(*args, **kwargs)
SysCallError: (104, 'Connection reset by peer')

**Comment by adamcik** [comment] 2016-01-05 10:00
@ernesst you issue is deep inside `gmusicapi` based on the traceback. The version you are using doesn't seem to have proper error handling of certain error cases from `requests`. Please try upgrading your versions and if that doesn't fix it file a bug against `gmusicapi` as this is not related to this issue.

**Comment by adamcik** [comment] 2016-01-05 10:01
As for the original issue, it seems we still have some issues with our playlist handling. This should be double checked and fixed in a 1.1.x release.

**Comment by jodal** [comment] 2016-01-10 07:48
I've added `http://downloads.bbc.co.uk/podcasts/radio4/myshakespeare/rss.xml` to my `podcast/feeds`, but cannot reproduce this issue.

@AnsgarSchmidt Can you still reproduce it?

I'd like to be able to reproduce this issue myself to study where in `_unwrap_stream` the `uri` variable is set to `None`. Either `uri` is initially `None` or we get a list of URIs back from `mopidy.internal.playlists.parse()` where the first URI is `None`.

**Comment by AnsgarSchmidt** [comment] 2016-01-10 14:56
Hi,
I haven't added the feed as a podcast in this case. My "radio application" reads several podcast feeds and playlists and calculates a new playlist to play. Some kind of very personalized radio. Among several others I also add the BBC ones and when mopidy comes to the point when to play the mp3 from bbc it crashes. Other podcasts are working fine, so it's not a general problem with the MP3 over URL. 

So in order to reproduce it can you try to "mpc add url" this:

http://open.live.bbc.co.uk/mediaselector/5/redir/version/2.0/mediaset/audio-nondrm-download/proto/http/vpid/p02r4wlz.mp3

and

http://open.live.bbc.co.uk/mediaselector/5/redir/version/2.0/mediaset/audio-nondrm-download/proto/http/vpid/p02r5219.mp3

and see if it crashes at your place?

Thanks a lot
Ansgar

**Comment by jodal** [comment] 2016-01-18 20:15
Both URLs work with `mpc add $url` for me:

```
$ mpc playlist
BBC Radio 4 - MyShakespeare: Shami Chakrabarti
BBC Radio 4 - MyOwnShakespeare: Jane Glover 15 May 12
```

I tested both with the release-1.1 branch and the 1.1.1 release.

Anyone else that can reproduce this?

**Comment by adamcik** [comment] 2016-02-15 20:55
We should retest this with 2.0 and the stream unwrap fixes that went in.

**Comment by AnsgarSchmidt** [comment] 2016-03-23 08:55
It works not with version 2.0.0-1 for me. No problem playing the bbc podcast. Although I have a new (maybe related) problem with podcasts now since the 2.0.0-1 version. When podcasts doesn't have meta information mopidy hangs for >30 minutes before and after playing the file. Don't know if this is related or a new phenomena. I triple checked my internet connection no problem there. 

My setup is:
2 songs
1 podcast added via mpc add http://
2 songs

The songs are from spotify and I have no problem there.

**Closed** 2016-05-01 21:39 UTC
Labels: Bug
