### ISSUE TITLE
GStreamer warning: "No volume control found"

### ISSUE THREAD

**Issue by itzekocke** [mopidy/mopidy#1458] opened 2016-02-19 21:35 UTC
Hi,

I recently installed Mopidy on a Raspberry Pi 2B with HiFiBerry DAC+ based on Ubuntu Mate 15.10 (4.1.15-v7+). The problem is this warning that prevents me from hearing any sound played by Mopidy (like a Spotify song):

> WARNING [1880:MainThread] mopidy.audio.gst: GStreamer warning: gst-stream-error-quark: No volume control found (3)

I installed GStreamer 0.1 and 1.0 including all available plugins - without any change.

However, the sound device works fine if I rund for example this command:

> speaker-test -c2 -D hw:1,0

Any help appreciated - after reading tons of hints this post feels like the last chance ...

Gerold

**Comment by Necrathex** [comment] 2016-02-22 08:39
Having the same issue with Mopidy 2.0.0 on Ubuntu:

> WARNING [5654:MainThread] mopidy.audio.gst: GStreamer warning: No volume control found
> ERROR [5654:MainThread] mopidy.audio.gst: GStreamer error: Internal data stream error.

Worked fine on 1.1.1

**Comment by jodal** [comment] 2016-02-22 12:39
This is probably fixed by commit 1e8bef25d36e1c257a369ff0ce5729c2939f384e which is in both the release-2.0 and develop branch. Keeping this open until confirmed.

**Comment by itzekocke** [comment] 2016-02-22 18:07
Hi Jodal,
thanks for the quick reply and development. I tried to run including the latest changes you made - without success.

However, it seems to be not a Mopidy issue (solely).

This is the output of 

> $ gst-launch audiotestsrc ! audioconvert ! audioresample ! alsasink
(syslog)

> Feb 22 18:57:39 hifiberry2 kernel: [154183.862349] pcm512x 1-004d: No SCLK, using BCLK: -2
> Feb 22 18:57:39 hifiberry2 rsyslogd-2007: action 'action 10' suspended, next retry is Mon Feb 22 18:59:09 2016 [v8.12.0 try http://www.rsyslog.com/e/2007 ]
> Feb 22 18:57:42 hifiberry2 pulseaudio[3464]: [alsa-sink-HiFiBerry DAC+ HiFi pcm512x-hifi-0] alsa-sink.c: ALSA woke us up to write new data to the devce, but there was actually nothing to write!
> Feb 22 18:57:42 hifiberry2 pulseaudio[3464]: [alsa-sink-HiFiBerry DAC+ HiFi pcm512x-hifi-0] alsa-sink.c: Most likely this is a bug in the ALSA driver 'snd_soc_hifiberry_dacplus'. Please report this issue to the ALSA developers.
> Feb 22 18:57:42 hifiberry2 pulseaudio[3464]: [alsa-sink-HiFiBerry DAC+ HiFi pcm512x-hifi-0] alsa-sink.c: We were woken up with POLLOUT set -- however a subsequent snd_pcm_avail() returned 0 or another value < min_avail.
> 

I decided to try again with a new image (Raspbian). I'll let you know the results.

Best
Gerold

**Comment by jodal** [comment] 2016-02-22 18:24
You're right, the warning is probably a red herring not related to your issue with not getting any sound. Due to the appropriate title of this issue I'm adopting it to track the issue of getting rid of the warning.

Hoping it works out with the new image. If not, try asking for help at https://discuss.mopidy.com :-)

**Comment by adamcik** [comment] 2016-02-22 19:19
To the best of my knowledge this warning is just telling us that using the playbin volume controls wouldn't work. No as we don't use playbin's volume control this would never break anything. It's just noise.

**Comment by jodal** [comment] 2016-03-26 10:57
Closing as the warning should be gone after the mentioned commit. The red herring warning is not present in the last log output provided, so it is not a reason to keep this open.

**Comment by adamcik** [comment] 2016-03-26 10:59
I would still want to slightly change how we solve this.

**Comment by adamcik** [comment] 2016-03-26 20:31
4bbd847a6a508b5bba7668e3847f2e3c721401c5 should do it.

**Closed by adamcik** 2016-03-26 20:31 UTC
Labels: Bug

**Comment by kdbdallas** [comment] 2016-04-10 15:37
I am getting this same error so I uninstalled, installed the git version (branch release-2.0) and I am still getting the error when I try and play. I can play audio via my Shairport-Sync setup just fine.

WARNING  2016-04-10 08:29:12,059 [6024:MainThread] mopidy.audio.gst
  GStreamer warning: gst-stream-error-quark: No volume control found (3)

**Comment by dmbuchta** [comment] 2016-05-27 01:44
This is happening to me on my rPi3 and I am using mopidy Version: 2.0.0-1.
