### ISSUE TITLE
MemoryError prevents Mopidy from starting

### ISSUE THREAD

**Issue by dirkgroenen** [mopidy/mopidy#1395] opened 2016-01-16 13:01 UTC
Ok so I just encountered some (weird) error on my Raspberry 2 which is running the latest Mopidy icw Mopify:

I was fiddling around in my house when Mopidy suddenly started lacking in playing music. I logged in into the Pi and noticed the CPU being at a full blown 100%, taken by the syslog. After tailing the syslog I saw a rapidly scrolling wall of `from tornado.ioloop import IOLoop, MemoryError` errors. I decided to kill mopidy, which stopped the errors, and reboot the Pi. 

After the reboot I wasn't able to get Mopidy working agian. The `MemoryError` error prevented it from starting. I checked my memory usage and it gave me the following result:

```
pi@raspberrypi:~ $ free -m
                    total       used       free     shared    buffers     cached
Mem:           925        759        166         40         23        686
-/+ buffers/cache:         50        875
Swap:           99          0         99

```

As you can see my memory looks full, but it's mostly taken by `/buffers/cache`, which means that it's [actually not full](http://www.linuxatemyram.com/). Just to be sure I cleaned the `buffers/cache` using 
`$ sync && echo 3 | sudo tee /proc/sys/vm/drop_caches ` and guess what, it started working again. 

I know/think this issue is probably more related to Tornado, but in case it is this might be able to help other's having the same issue.

**Comment by jodal** [comment] 2016-01-17 20:51
When you're out of memory, most apps will works badly, and Python will start throwing a lot of `MemoryError`. When this ends up in the log, it's not helping much with the already swamped memory. Point is, I'm not sure Tornado is to blame here, I might just happen to be the thing in Mopidy doing work when the memory ran out, and got stuck in some loop trying to do something that failed every time because of `MemoryError`.

If you're on Raspbian Jessie, I guess you could configure your systemd journal to only grow to a limited size and then start throwing out the oldest log. That way you'll never go above e.g. 100MB of logs.

Unless your or someone else can reproduce this in the near future (say a month) and find more clues to the cause of this, I don't think there's much else to do than close this.

**Comment by adamcik** [comment] 2016-02-15 22:08
Any thing we can actually do about this?

**Comment by jodal** [comment] 2016-02-15 22:14
Don't think so, and 29 days is close enough to a month.

**Closed by jodal** 2016-02-15 22:14 UTC
