### ISSUE TITLE
Error mapping GST state

### ISSUE THREAD

**Issue by trygveaa** [mopidy/mopidy#1430] opened 2016-02-05 23:23 UTC
I played around with stuff adding and playing tracks etc. Not sure what triggered this.

```
Traceback (most recent call last):
  File "/home/trygve/dev/mopidy/mopidy/mopidy/audio/actor.py", line 210, in on_message
    self.on_playbin_state_changed(old_state, new_state, pending_state)
  File "/home/trygve/dev/mopidy/mopidy/mopidy/audio/actor.py", line 260, in on_playbin_state_changed
    target_state = _GST_STATE_MAPPING[self._audio._target_state]
KeyError: <enum GST_STATE_READY of type GstState>
```

**Comment by jodal** [comment] 2016-02-10 21:24
Am I right that this is a duplicate of #1222?

Does this lead to Mopidy being unusable, or does everything still seem to work?

**Comment by trygveaa** [comment] 2016-02-10 21:43
Yes, this is a duplicate. I hadn't seen/didn't remember #1222 when opening this. @adamcik said this on IRC after I opened this:

> 11:46:50 <+adamcik> trygveaa: #1430 is kinda a dupe if race free audio. At least the same error is what triggered that bug
> 11:51:38 <+adamcik> But we might just want to solve 1430 with a workaround and use the other issue to track a systematic fix of audio with respect to this

I think everything still worked after this happened.

**Comment by adamcik** [comment] 2016-02-10 21:58
Quick fix is just to consider `READY == PAUSED`, it's not correct, and might show some weird results, but it won't break anything. So it's better than having these random errors.

**Closed** 2016-02-13 19:57 UTC
Labels: bug
