### ISSUE TITLE
Soundcloud - pykka.exceptions.ActorDeadError: MpdSession

### ISSUE THREAD

**Issue by karan** [mopidy/mopidy#945] opened 2015-01-21 19:18 UTC
While using mopidy with ncmpc, I tried to get the liked songs from Soundcloud, but get this:

```
$ mopidy 
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
INFO     Starting Mopidy 0.19.5
INFO     Loading config from: builtin defaults, /etc/xdg/mopidy/mopidy.conf, /Users/karan/.config/mopidy/mopidy.conf, command line options
INFO     Enabled extensions: mpd, http, stream, softwaremixer, local, soundcloud
INFO     Disabled extensions: none
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Mixing using GStreamer software mixing
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: LocalBackend, StreamBackend, SoundCloudBackend
INFO     Loaded 0 local playlists from /Users/karan/.local/share/mopidy/local/playlists
INFO     No local library metadata cache found at /Users/karan/.local/share/mopidy/local/library.json.gz. Please run `mopidy local scan` to index your local music library. If you do not have a local music collection, you can disable the local backend to hide this message.
INFO     Loaded 0 local tracks using json
INFO     Audio output set to "autoaudiosink"
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: MpdFrontend, HttpFrontend
INFO     MPD server running at [::ffff:127.0.0.1]:6600
INFO     HTTP server running at [::ffff:127.0.0.1]:6680
INFO     New MPD connection from [::ffff:127.0.0.1]:57719
INFO     'Deep Faded (3LAU Mashup)' can't be streamed from SoundCloud
INFO     New MPD connection from [::ffff:127.0.0.1]:57724
INFO     'Deep Faded (3LAU Mashup)' can't be streamed from SoundCloud
INFO     New MPD connection from [::ffff:127.0.0.1]:57727
INFO     'Deep Faded (3LAU Mashup)' can't be streamed from SoundCloud
INFO     New MPD connection from [::ffff:127.0.0.1]:57732
INFO     'Hanging On (I See MONSTAS Remix)' can't be streamed from SoundCloud
INFO     'Idina Menzel - Let It Go (Armin van Buuren Remix) [A State Of Trance Episode 658]' can't be streamed from SoundCloud
INFO     'Avicii 'Levels' Skrillex Remix' can't be streamed from SoundCloud
ERROR    Unhandled exception in MpdSession (urn:uuid:c8777109-daf8-4eeb-bdb2-fd32e2a80886):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 303, in _handle_receive
    return self.on_receive(message)
  File "/usr/local/lib/python2.7/site-packages/mopidy/utils/network.py", line 366, in on_receive
    self.on_line_received(line)
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/session.py", line 33, in on_line_received
    response = self.dispatcher.handle_request(line)
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 46, in handle_request
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 75, in _catch_mpd_ack_errors_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 85, in _authenticate_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 104, in _command_list_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 133, in _idle_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 146, in _add_ok_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 158, in _call_handler_filter
    response = self._format_response(self._call_handler(request))
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 167, in _call_handler
    return protocol.commands.call(tokens, context=self.context)
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/protocol/__init__.py", line 178, in call
    return self.handlers[tokens[0]](context, *tokens[1:])
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/protocol/__init__.py", line 156, in validate
    return func(**callargs)
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/protocol/music_db.py", line 413, in lsinfo
    for path, lookup_future in context.browse(uri, recursive=False):
  File "/usr/local/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 319, in browse
    for ref in future.get():
  File "/usr/local/lib/python2.7/site-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/site-packages/mopidy/core/library.py", line 73, in browse
    return backend.library.browse(uri).get()
  File "/usr/local/lib/python2.7/site-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/local/lib/python2.7/site-packages/mopidy_soundcloud/library.py", line 148, in browse
    return self.list_liked()
  File "/usr/local/lib/python2.7/site-packages/mopidy_soundcloud/library.py", line 60, in list_liked
    logger.debug('Adding liked track %s to vfs' % data.name)
AttributeError: 'list' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mopidy/utils/network.py", line 272, in recv_callback
    self.actor_ref.tell({'close': True})
  File "/usr/local/lib/python2.7/site-packages/pykka/actor.py", line 437, in tell
    raise _ActorDeadError('%s not found' % self)
pykka.exceptions.ActorDeadError: MpdSession (urn:uuid:c8777109-daf8-4eeb-bdb2-fd32e2a80886) not found
INFO     New MPD connection from [::ffff:127.0.0.1]:57741
```

Here's what my conf file looks like:

```
[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600
#password = 
#max_connections = 20
#connection_timeout = 60
#zeroconf = Mopidy MPD server on $hostname

[http]
enabled = true
hostname = 127.0.0.1
port = 6680
#static_dir =
#zeroconf = Mopidy HTTP server on $hostname

[stream]
enabled = true

[soundcloud]
auth_token = 1-35204-xxxxxxx-xxxxxxxxxxxxx
```

**Comment by adamcik** [comment] 2015-01-21 19:23
Dupe of https://github.com/mopidy/mopidy-soundcloud/issues/43 - so if this leaves the MPD frontend in an unusable state then there is bug we need to fix on the mopidy side, otherwise it is just a mopidy-soundcloud issue. Feel free to reopen if we need to fix something in mopidy itself.

**Closed by adamcik** 2015-01-21 19:23 UTC
