### ISSUE TITLE
Apple Music backend

### ISSUE THREAD

**Issue by adtac** [mopidy/mopidy#1696] opened 2018-08-20 16:23 UTC
Hi, I've tried searching for this everywhere and I *think* there's no duplicate issue. Has a backend for Apple Music been discussed before? Apple offers a Apple Music API, so I imagine this must be possible (I haven't checked thoroughly).

**Comment by agg23** [comment] 2018-09-03 15:03
[It is most certainly possible.](https://github.com/zachomedia/apple-music-webplayer)

**Comment by agg23** [comment] 2018-09-16 18:27
I stand corrected. I began building the backend, but found that while iTunes Match tracks are unencrypted (tracks that you upload), Apple Music tracks are encrypted using either Widevine or Fairplay. It seems that there is no known way to decrypt either system in GStreamer or FFMPEG, so I think we're out of luck.

My work is available here https://github.com/agg23/Mopidy-AppleMusic

**Comment by Provessor** [comment] 2018-11-01 07:07
Have you seen this?
https://medium.com/combo-fm/navigating-the-apple-music-ios-api-e9dd2c3ea65a

I'm too busy right now to try it out but if nothing has changed in a couple of weeks then I'm free to look into it some more

**Comment by LKLAW** [comment] 2019-06-26 10:24
How hard is it to implement this:
https://pypi.org/project/apple-music-python/

**Comment by agg23** [comment] 2019-06-26 13:06
That API doesn't add anything new over what we already have. The issue is with the encryption of the tracks.

**Comment by LKLAW** [comment] 2019-06-26 13:17
So it's because of they way MusicKit works that it can't be implemented?

**Comment by V3L** [comment] 2019-09-15 23:56
Should this be possible now if sites like https://musi.sh allow you to play tracks from apple music in a browser? This is also created using the MusicKit API.

**Comment by agg23** [comment] 2019-09-16 00:18
To my knowledge, nothing has changed. There is some very low-level code in Chromium/Firefox that allows Widevine to be decrypted. When I worked on this a year ago, Widevine had not been extracted in a useful manner (say into FFmpeg). If there is no way to decrypt the files outside of a browser, then custom backends such as for Mopidy aren't really possible.

**Comment by adamcik** [comment] 2019-11-27 19:44
https://discourse.mopidy.com/t/supporting-new-streaming-services-and-other-music-sources/22/2 is our general advice for adding new extensions. I've not looked at if it would be possible for this one in particular, but it would need someone else to make the extension as we have our hands full with just mopidy itself.

As such I'm closing this issue as it's not a bug or feature request for Mopidy itself.

**Closed by adamcik** 2019-11-27 19:44 UTC
Labels: C-extension-request
