### ISSUE TITLE
Core dumped when playing finish

### ISSUE THREAD

**Issue by joksnet** [mopidy/mopidy#1274] opened 2015-09-02 14:49 UTC
Sometimes I got a *core dumped* when the current songs finish playing. I don't know exactly when. If I put just one song, plays and finish well, sometimes a whole album plays and finish without error. But sometimes when an album finish playing, mopidy die with a core dumped.

Here is the output:

```
INFO     2015-09-02 11:44:47,435 [7297:MainThread] mopidy.__main__
  Starting Mopidy 1.1.0
DEBUG    2015-09-02 11:44:47,439 [7297:MainThread] mopidy.ext
  Loading entry point: mpd = mopidy.mpd:Extension
DEBUG    2015-09-02 11:44:47,439 [7297:MainThread] mopidy.ext
  Loaded extension: Mopidy-MPD 1.1.0
DEBUG    2015-09-02 11:44:47,439 [7297:MainThread] mopidy.ext
  Loading entry point: http = mopidy.http:Extension
DEBUG    2015-09-02 11:44:47,439 [7297:MainThread] mopidy.ext
  Loaded extension: Mopidy-HTTP 1.1.0
DEBUG    2015-09-02 11:44:47,439 [7297:MainThread] mopidy.ext
  Loading entry point: stream = mopidy.stream:Extension
DEBUG    2015-09-02 11:44:47,439 [7297:MainThread] mopidy.ext
  Loaded extension: Mopidy-Stream 1.1.0
DEBUG    2015-09-02 11:44:47,439 [7297:MainThread] mopidy.ext
  Loading entry point: m3u = mopidy.m3u:Extension
DEBUG    2015-09-02 11:44:47,440 [7297:MainThread] mopidy.ext
  Loaded extension: Mopidy-M3U 1.1.0
DEBUG    2015-09-02 11:44:47,440 [7297:MainThread] mopidy.ext
  Loading entry point: softwaremixer = mopidy.softwaremixer:Extension
DEBUG    2015-09-02 11:44:47,440 [7297:MainThread] mopidy.ext
  Loaded extension: Mopidy-SoftwareMixer 1.1.0
DEBUG    2015-09-02 11:44:47,440 [7297:MainThread] mopidy.ext
  Loading entry point: file = mopidy.file:Extension
DEBUG    2015-09-02 11:44:47,440 [7297:MainThread] mopidy.ext
  Loaded extension: Mopidy-File 1.1.0
DEBUG    2015-09-02 11:44:47,440 [7297:MainThread] mopidy.ext
  Loading entry point: local = mopidy.local:Extension
DEBUG    2015-09-02 11:44:47,441 [7297:MainThread] mopidy.ext
  Loaded extension: Mopidy-Local 1.1.0
DEBUG    2015-09-02 11:44:47,441 [7297:MainThread] mopidy.ext
  Discovered extensions: mpd, http, stream, m3u, softwaremixer, file, local
INFO     2015-09-02 11:44:47,444 [7297:MainThread] mopidy.config
  Loading config from builtin defaults
DEBUG    2015-09-02 11:44:47,445 [7297:MainThread] mopidy.config
  Loading config from /etc/xdg/mopidy/mopidy.conf failed; it does not exist
INFO     2015-09-02 11:44:47,445 [7297:MainThread] mopidy.config
  Loading config from /home/jm/.config/mopidy/mopidy.conf
INFO     2015-09-02 11:44:47,447 [7297:MainThread] mopidy.config
  Loading config from command line options
DEBUG    2015-09-02 11:44:47,449 [7297:MainThread] mopidy.ext
  Validating extension: mpd
DEBUG    2015-09-02 11:44:47,449 [7297:MainThread] mopidy.ext
  Validating extension: http
DEBUG    2015-09-02 11:44:47,473 [7297:MainThread] mopidy.ext
  Validating extension: stream
DEBUG    2015-09-02 11:44:47,473 [7297:MainThread] mopidy.ext
  Validating extension: m3u
DEBUG    2015-09-02 11:44:47,473 [7297:MainThread] mopidy.ext
  Validating extension: softwaremixer
DEBUG    2015-09-02 11:44:47,474 [7297:MainThread] mopidy.ext
  Validating extension: file
DEBUG    2015-09-02 11:44:47,474 [7297:MainThread] mopidy.ext
  Validating extension: local
INFO     2015-09-02 11:44:47,474 [7297:MainThread] mopidy.__main__
  Enabled extensions: mpd, stream, m3u, softwaremixer, file, local
INFO     2015-09-02 11:44:47,475 [7297:MainThread] mopidy.__main__
  Disabled extensions: http
DEBUG    2015-09-02 11:44:47,494 [7297:MainThread] mopidy.commands
  Available Mopidy mixers: SoftwareMixer
INFO     2015-09-02 11:44:47,494 [7297:MainThread] mopidy.commands
  Starting Mopidy mixer: SoftwareMixer
DEBUG    2015-09-02 11:44:47,495 [7297:MainThread] pykka
  Registered SoftwareMixer (urn:uuid:f7a9faa8-29c3-4562-90a7-f7ae78f59b34)
DEBUG    2015-09-02 11:44:47,495 [7297:MainThread] pykka
  Starting SoftwareMixer (urn:uuid:f7a9faa8-29c3-4562-90a7-f7ae78f59b34)
DEBUG    2015-09-02 11:44:47,495 [7297:MainThread] mopidy.commands
  Mixer volume left unchanged
INFO     2015-09-02 11:44:47,495 [7297:MainThread] mopidy.commands
  Starting Mopidy audio
DEBUG    2015-09-02 11:44:47,496 [7297:MainThread] pykka
  Registered Audio (urn:uuid:9e18536c-4bff-4da7-a06d-141801826ff0)
DEBUG    2015-09-02 11:44:47,496 [7297:MainThread] pykka
  Starting Audio (urn:uuid:9e18536c-4bff-4da7-a06d-141801826ff0)
INFO     2015-09-02 11:44:47,496 [7297:MainThread] mopidy.commands
  Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, LocalBackend
DEBUG    2015-09-02 11:44:47,498 [7297:MainThread] pykka
  Registered StreamBackend (urn:uuid:3c721eae-0632-400b-ac73-d2ba136da7dc)
DEBUG    2015-09-02 11:44:47,498 [7297:MainThread] pykka
  Starting StreamBackend (urn:uuid:3c721eae-0632-400b-ac73-d2ba136da7dc)
INFO     2015-09-02 11:44:47,499 [7297:MainThread] mopidy.m3u.playlists
  Loaded 0 M3U playlists from /home/jm/.local/share/mopidy/m3u
DEBUG    2015-09-02 11:44:47,500 [7297:MainThread] pykka
  Registered M3UBackend (urn:uuid:1fb9d0c1-6f31-48dc-a45d-50dea9adcc2f)
DEBUG    2015-09-02 11:44:47,500 [7297:MainThread] pykka
  Starting M3UBackend (urn:uuid:1fb9d0c1-6f31-48dc-a45d-50dea9adcc2f)
INFO     2015-09-02 11:44:47,500 [7297:Audio-2] mopidy.audio.actor
  Audio output set to "autoaudiosink"
WARNING  2015-09-02 11:44:47,500 [7297:MainThread] mopidy.file.library
  Failed expanding path ($XDG_MUSIC_DIR) fromfile/media_dirs config value.
DEBUG    2015-09-02 11:44:47,501 [7297:MainThread] pykka
  Registered FileBackend (urn:uuid:387fd7e6-4dd7-425d-a464-dbe1ff81d73e)
DEBUG    2015-09-02 11:44:47,501 [7297:MainThread] pykka
  Starting FileBackend (urn:uuid:387fd7e6-4dd7-425d-a464-dbe1ff81d73e)
DEBUG    2015-09-02 11:44:47,502 [7297:MainThread] mopidy.local.actor
  Using json as the local library
DEBUG    2015-09-02 11:44:47,502 [7297:MainThread] mopidy.local.json
  Loading library: /home/jm/.local/share/mopidy/local/library.json.gz
INFO     2015-09-02 11:44:48,760 [7297:MainThread] mopidy.local.library
  Loaded 6936 local tracks using json
DEBUG    2015-09-02 11:44:48,760 [7297:MainThread] pykka
  Registered LocalBackend (urn:uuid:68795df6-7062-416e-8f91-3644058a334c)
DEBUG    2015-09-02 11:44:48,760 [7297:MainThread] pykka
  Starting LocalBackend (urn:uuid:68795df6-7062-416e-8f91-3644058a334c)
INFO     2015-09-02 11:44:48,761 [7297:MainThread] mopidy.commands
  Starting Mopidy core
DEBUG    2015-09-02 11:44:48,763 [7297:MainThread] pykka
  Registered Core (urn:uuid:0551c2f6-5168-459e-9fed-1888d45a8f29)
DEBUG    2015-09-02 11:44:48,763 [7297:MainThread] pykka
  Starting Core (urn:uuid:0551c2f6-5168-459e-9fed-1888d45a8f29)
INFO     2015-09-02 11:44:48,770 [7297:MainThread] mopidy.commands
  Starting Mopidy frontends: MpdFrontend
INFO     2015-09-02 11:44:48,771 [7297:MainThread] mopidy.mpd.actor
  MPD server running at [::ffff:127.0.0.1]:6600
DEBUG    2015-09-02 11:44:48,771 [7297:MainThread] pykka
  Registered MpdFrontend (urn:uuid:3c37f08f-e099-4d5b-b7f0-bac87d8d8b6e)
DEBUG    2015-09-02 11:44:48,771 [7297:MainThread] pykka
  Starting MpdFrontend (urn:uuid:3c37f08f-e099-4d5b-b7f0-bac87d8d8b6e)
DEBUG    2015-09-02 11:44:48,772 [7297:MpdFrontend-8] mopidy.zeroconf
  Zeroconf service _mpd._tcp at [localhost.localdomain.local]:6600: Avahi service not running; publish failed.
DEBUG    2015-09-02 11:44:49,171 [7297:MainThread] pykka
  Registered MpdSession (urn:uuid:329de725-db5f-4e08-9893-ca88662dda91)
DEBUG    2015-09-02 11:44:49,171 [7297:MainThread] pykka
  Starting MpdSession (urn:uuid:329de725-db5f-4e08-9893-ca88662dda91)
INFO     2015-09-02 11:44:49,171 [7297:MpdSession-9] mopidy.mpd.session
  New MPD connection from [::ffff:127.0.0.1]:38840
DEBUG    2015-09-02 11:44:49,172 [7297:MpdSession-9] mopidy.mpd.session
  Request from [::ffff:127.0.0.1]:38840: password "ar668"
DEBUG    2015-09-02 11:44:49,172 [7297:MpdSession-9] mopidy.mpd.session
  Response to [::ffff:127.0.0.1]:38840: OK
DEBUG    2015-09-02 11:44:49,173 [7297:MpdSession-9] mopidy.mpd.session
  Request from [::ffff:127.0.0.1]:38840: status
DEBUG    2015-09-02 11:44:49,192 [7297:MpdSession-9] mopidy.mpd.session
  Response to [::ffff:127.0.0.1]:38840: 
    volume: 100
    repeat: 0
    random: 0
    single: 0
    consume: 0
    playlist: 0
    playlistlength: 0
    xfade: 0
    state: stop
    OK



[...]



DEBUG    2015-09-02 11:33:47,068 [7897:MpdSession-9] mopidy.mpd.session
  Request from [::ffff:127.0.0.1]:56578: currentsong
DEBUG    2015-09-02 11:33:47,069 [7897:MpdSession-9] mopidy.mpd.session
  Response to [::ffff:127.0.0.1]:56578: 
    file: local:track:Varios/Ska-P/1996%20-%20El%20vals%20del%20obrero/09%20-%20Insecto%20urbano.mp3
    Time: 252
    Artist: Ska-P
    Album: El vals del obrero
    Title: Insecto urbano
    Date: 1996-01-01
    Track: 9
    Pos: 8
    Id: 37
    Genre: Ska
    Last-Modified: 2006-07-17T09:06:28Z
    OK
DEBUG    2015-09-02 11:33:47,467 [7897:MainThread] mopidy.audio.gst
  Got end-of-stream message.
DEBUG    2015-09-02 11:33:47,467 [7897:MainThread] mopidy.audio.actor
  Audio event: reached_end_of_stream()
DEBUG    2015-09-02 11:33:47,467 [7897:MainThread] mopidy.listener
  Sending reached_end_of_stream to AudioListener: {}
DEBUG    2015-09-02 11:33:47,469 [7897:MainThread] mopidy.audio.gst
  Got state-changed message: old=GST_STATE_PLAYING new=GST_STATE_PAUSED pending=GST_STATE_NULL
g_mutex_clear() called on uninitialised or locked mutex
[1]    7897 abort (core dumped)  mopidy -vvv
```

I don't know where to start debugging this. Any help of how to process will be appreciated.

**Comment by joksnet** [comment] 2015-09-07 13:38
I have two different signals.

```
$ coredumpctl info 8408
           PID: 8408 (mopidy)
           UID: 1000 (jm)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Sat 2015-09-05 14:15:13 ART (1 day 20h ago)
  Command Line: /usr/bin/python2 /usr/bin/mopidy
    Executable: /usr/bin/python2.7
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (jm)
       Boot ID: e63a8727b3654980bccd7062ec0d0811
    Machine ID: a63100a474d5407a94632c0b909438aa
      Hostname: take
       Message: Process 8408 (mopidy) of user 1000 dumped core.
```
```
$ coredumpctl info 7599
           PID: 7599 (mopidy)
           UID: 1000 (jm)
           GID: 100 (users)
        Signal: 6 (ABRT)
     Timestamp: Mon 2015-09-07 10:26:22 ART (4min 38s ago)
  Command Line: /usr/bin/python2 /usr/bin/mopidy
    Executable: /usr/bin/python2.7
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (jm)
       Boot ID: e63a8727b3654980bccd7062ec0d0811
    Machine ID: a63100a474d5407a94632c0b909438aa
      Hostname: take
       Message: Process 7599 (mopidy) of user 1000 dumped core.
```

**Comment by jodal** [comment] 2015-09-22 19:57
This looks like a duplicate of #933.

**Closed by jodal** 2015-09-22 19:57 UTC
