### ISSUE TITLE
auto scan songs

### ISSUE THREAD

**Issue by lvaccaro** [mopidy/mopidy#1279] opened 2015-09-10 10:58 UTC
I need to retrieve the list of the current available song. When I move a new file in the media_dir, the list of songs are not automatically updated. I need to stop the server and run ` mopidy local scan --force ` and start the server again. If I try to run the previous command on another instance (without stop the server) the songs are not refreshed.

Config file:
`media_dir = /var/lib/mopidy/media`
`scan_timeout = 1000`

Command to retrieve list of songs:
`ws://localhost:6680/mopidy/ws`
`{jsonrpc:2.0 , id : 1 , method : core.library.browse , params : { uri : "local:directory" }}`

mopidy version 1.1.0

**Comment by adamcik** [comment] 2015-09-10 11:11
Duplicate of #666, closing this copy :-)

**Closed by adamcik** 2015-09-10 11:11 UTC

**Comment by kingosticks** [comment] 2015-09-10 11:18
It's also probably worth mentioning that if you switch to using [mopidy-local-sqlite](https://github.com/mopidy/mopidy-local-sqlite) (I assume you are using json) it will detect when you run `mopidy local scan` and new songs will be available without needing to restart Mopidy.

**Comment by tkem** [comment] 2015-09-11 16:52
And, since the OP is running Mopidy v1.1, let's not forget the new `file` extension - browsing "Files" doesn't require a `local scan`, but it has it's own configuration for `media_dirs`: https://docs.mopidy.com/en/latest/ext/file/

**Comment by lvaccaro** [comment] 2015-09-17 10:42
tkem, I set the file configuration and media_dirs. Anyway, when I make the request, I have no response:
`'{"jsonrpc": "2.0", "id": 1, "method": "core.library.browse", "params":  { "uri"  :  "file:directory" }  }`
When I start mopidy, the extension is enabled:
`INFO     Starting Mopidy 1.1.0
....
INFO     Enabled extensions: mpd, http, m3u, softwaremixer, file, musicbox_webclient, local-sqlite`
