### ISSUE TITLE
Mopidy v1.0.1 no longer sends mute_changed events on core.mixer.set_mute()

### ISSUE THREAD

**Issue by tkem** [mopidy/mopidy#1146] opened 2015-04-25 12:42 UTC
See
https://gist.github.com/tkem/4e1ce8178ca792cb427e
vs.
https://gist.github.com/tkem/734d7190874739d06f0b

This effectively breaks Mopidy-Mobile's "mute" button (though relying on the changed event for giving user feedback may be questionable in itself).

**Comment by adamcik** [comment] 2015-04-25 15:41
Sounds like a regression we can and should fix. Since a lot of these things have the pattern make the change, wait for the event to show it actually happened.

**Comment by adamcik** [comment] 2015-04-25 15:41
But not sure off the top of my head if say mopidy-alsamixer does this right.

**Comment by jodal** [comment] 2015-04-26 21:51
Fixed in PR #1152.

**Closed by jodal** 2015-04-26 21:51 UTC
Labels: Audio, bug
