### ISSUE TITLE
ERROR [1853:Core-14] mopidy.core.playlists: M3UBackend backend caused an exception

### ISSUE THREAD

**Issue by arvinddeshpande** [mopidy/mopidy#1550] opened 2016-08-22 00:36 UTC
I am running mopidy 2.0.1 on Raspberry Pi 2 JESSIE with following modules

```
Mopidy==2.0.1
Mopidy-AlarmClock==0.1.5
Mopidy-Dirble==1.3.0
Mopidy-GMusic==1.0.0
Mopidy-InternetArchive==2.0.0
Mopidy-Local-SQLite==1.0.0
Mopidy-MusicBox-Webclient==2.3.0
Mopidy-Podcast==2.0.1
Mopidy-Podcast-iTunes==2.0.0
Mopidy-SomaFM==1.0.1
Mopidy-TuneIn==0.4.1
Mopidy-WebSettings==0.1.4.2
```

I get following error spewed in the logs. I tried searching for the error on Google but I do not see anyone reporting this. May be something wrong with my setup?

```
2016-08-21 13:52:55,317 INFO [1853:Thread-13] mopidy_gmusic.actor: Finished refreshing Google Music content in 2s
2016-08-21 13:52:55,980 ERROR [1853:Core-14] mopidy.core.playlists: M3UBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playlists.py", line 18, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/playlists.py", line 66, in as_list
    playlists = future.get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy/m3u/playlists.py", line 75, in as_list
    result.append(translator.path_to_ref(entry))
  File "/usr/lib/python2.7/dist-packages/mopidy/m3u/translator.py", line 76, in path_to_ref
    name=name_from_path(path)
  File "/usr/lib/python2.7/dist-packages/mopidy/models/__init__.py", line 77, in playlist
    return cls(**kwargs)
  File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 158, in __call__
    *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 34, in __init__
    self._set_field(key, value)
  File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 186, in _set_field
    object.__setattr__(self, name, value)
  File "/usr/lib/python2.7/dist-packages/mopidy/models/fields.py", line 50, in __set__
    value = self.validate(value)
  File "/usr/lib/python2.7/dist-packages/mopidy/models/fields.py", line 101, in validate
    return compat.intern(value)
TypeError: can't intern subclass of string
2016-08-21 14:52:55,327 INFO [1853:Thread-13] mopidy_gmusic.actor: Start refreshing Google Music playlists
```

**Comment by tkem** [comment] 2016-08-22 06:30
Hmmm... Do you have any M3U playlists with non-ASCII characters in their file names? Did your setup work with earlier versions of Mopidy? Did you change your system locale?

**Comment by Chudders** [comment] 2016-08-22 15:53
HI, as you know (I think) having the same issue. 

> > Hullo.
> 
> I'm rather new to all this but have managed to get Mopidy working smoothly on a Raspberry Pi following the excellent instructions on the Mopidy website. Everything with the exception of the playlist backend. I get this error:
> 
> 

> ERROR M3UBackend backend caused an exception.
> > Traceback (most recent call last):
> > File "/usr/lib/python2.7/dist-packages/mopidy/core/playlists.py", line 18, in backenderror_handling
> > yield
> > File "/usr/lib/python2.7/dist-packages/mopidy/core/playlists.py", line 66, in as_list
> > playlists = future.get()
> > File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
> > compat.reraise(*self.data['excinfo'])
> > File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
> > exec('raise tp, value, tb')
> > File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in actorloop
> > response = self.handlereceive(message)
> > File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in handlereceive
> > return callee(*message['args'], **message['kwargs'])
> > File "/usr/lib/python2.7/dist-packages/mopidy/m3u/playlists.py", line 75, in as_list
> > result.append(translator.path_to_ref(entry))
> > File "/usr/lib/python2.7/dist-packages/mopidy/m3u/translator.py", line 76, in path_to_ref
> > name=name_from_path(path)
> > File "/usr/lib/python2.7/dist-packages/mopidy/models/__init__.py", line 77, in playlist
> > return cls(**kwargs)
> > File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 158, in call
> > *args, **kwargs)
> > File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 34, in init
> > self.setfield(key, value)
> > File "/usr/lib/python2.7/dist-packages/mopidy/models/immutable.py", line 186, in setfield
> > object.setattr(self, name, value)
> > File "/usr/lib/python2.7/dist-packages/mopidy/models/fields.py", line 50, in set
> > value = self.validate(value)
> > File "/usr/lib/python2.7/dist-packages/mopidy/models/fields.py", line 101, in validate
> > return compat.intern(value)
> > TypeError: can't intern subclass of string
> > I did try to point the config to a folder I've created but when the error came up I reset the config to default.

> 
> Other backends I'm running (and without issue are) all the other standard Mopidy ones (podcast, MPD, etc). As well as:
> 
> Spotify 
> Spotify tunigo
> Soundcloud
> Gmusic
> TuneIn
> Mopify
> 
> Any help would be much appreciated because at present I am unable to save any playlists and the red text annoys me greatly.
> 
> Ta v much!

Any playlists I have would have been imported from either Spotify or Google Music. The former might contain non ASCII characters as it goes.

**Comment by tkem** [comment] 2016-08-22 16:33
@Chudders: No, I specifically meant .m3u playlists in your `m3u/playlists_dir`.

**Comment by tkem** [comment] 2016-08-22 18:03
Wild guess (yes, I'm quite puzzled by this): Please post the output of

```
pip freeze | grep future
```
And, if you can live without `Mopidy-GMusic` for a while, try 
```
pip uninstall future
```
Thanks.

**Comment by tkem** [comment] 2016-08-22 18:14
On second though, you may also try uninstalling Mopidy-GMusic right away (*not* just disabling it in the `mopidy.conf`).

**Comment by tkem** [comment] 2016-08-22 18:24
FYI: Only reason I can find for this is related to the `future` package:
```
>>> import future
>>> from builtins import bytes
>>> s = bytes('abc')
>>> intern(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't intern subclass of string
```
AFAICS, the only Mopidy extension that uses `future` is `Mopidy-GMusic`, which both @arvinddeshpande  and @Chudders have installed. Though I installed `Mopidy-GMusic` myself, but can't reproduce the error...

**Comment by tkem** [comment] 2016-08-22 18:46
I was finally able to reproduce this, but strangely *only* on Raspbian, and *not* on Ubuntu 16.04...
Uninstalling `Mopidy-GMusic` did the trick, as I expected.
Why seems to be a Raspbian issue beats me, frankly; both my Raspbian and Ubuntu machines had `future==0.15.2` installed.

**Comment by arvinddeshpande** [comment] 2016-08-22 20:04
I think it's related to locale. For some reason Raspbian Jessie light thinks I'm in GB 

Sent from Yahoo Mail on Android 
 
  On Mon, Aug 22, 2016 at 1:46 PM, Thomas Kemmer<notifications@github.com> wrote:   
I was finally able to reproduce this, but strangely only on Raspbian, and not on Ubuntu 16.04...
Uninstalling Mopidy-GMusic did the trick, as I expected.
Why seems to be a Raspbian issue beats me, frankly; both my Raspbian and Ubuntu machines had future==0.15.2 installed.

**Comment by tkem** [comment] 2016-08-22 20:13
Did you try changing your locale? I have `en_US.UTF-8` on my Raspbian and still have the issue when installing `Mopidy-GMusic`.

**Comment by arvinddeshpande** [comment] 2016-08-22 23:02
Hey tkem,
My problem started as soon as I enabled Mopidy-GMusic/gpoddder/Dirble. I think tonight I might find more time to debug the code to see what exactly is causing it. May be put some debug statements to see what Playlist it's trying to create.
I've run **raspbian-config** and did set the locale to en_US.UTF8. But I was checking my /etc/wpa_supplicant/wpa_supplicant.conf and did notice first list to be =GB.
That's why I suspect somehow my locale is GB even though I've set it up to US.

But as you said, I don't think that'll make any difference. I will try to set it up to en_US.UTF8 and see what happens. 
I am just wondering how come no one else is reporting this problem. Cause search for M3UBackend exception doesn't even yield 3 Google pages.

**Comment by arvinddeshpande** [comment] 2016-08-23 01:24
Yes! I managed to change my locale to EN_US-UTF8 but I still have the same problem. translate.py isn't it trying to translate a name of the Google Playlist or something? 

Sent from Yahoo Mail on Android 
 
  On Mon, Aug 22, 2016 at 3:13 PM, Thomas Kemmer<notifications@github.com> wrote:   
Did you try changing your locale? I have en_US.UTF-8 on my Raspbian and still have the issue when installing Mopidy-GMusic.

**Comment by arvinddeshpande** [comment] 2016-08-23 01:28
BTW 
pip freeze ¦ grep future
future = 0.15.2

**Comment by tkem** [comment] 2016-08-23 05:39
My current (somewhat educated) guess is that this *not* related to locales, but a side-effect of the `future` module, which replaces the built-in `bytes` type.
Specifically, using `future`, `intern(bytes())` no longer works. At least that what comes up when you search for the original `TypeError` message.
Mopidy uses `intern()` to reduce memory usage in its models, for example for URIs. M3U uses `bytes` objects for its URIs, as do some other backends IIRC (local, file?).
Still need some time to verify this, though.

**Comment by tkem** [comment] 2016-08-23 05:43
@arvinddeshpande: The m3u backend handles M3U playlists (files) *only* and is blissfully ignorant of Google or Spotify playlists.

**Comment by tkem** [comment] 2016-08-23 08:57
@jodal, @adamcik: I just discovered that Python3 will only intern (Unicode) strings, and not bytes:
```
>>> import sys
>>> sys.intern(b'abc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: must be str, not bytes
```
So I'd suggest we either
- rethink the "interning" of Identifier fields (including URIs) in Mopidy models
- make sure Identifiers (including URIs) are always Unicode strings and not byte objects (which would also put an end to the URI data type discussion)

**Comment by jodal** [comment] 2016-08-23 10:38
With the port of Mopidy to Python 3, I believe that we'll change the type of file system paths to be Unicode strings as well, so :+1: to ensuring ~everything is a Unicode string, both URIs and file paths.

**Comment by Chudders** [comment] 2016-08-23 21:05
Hi, thanks all for your help with this. Just awesome.

Just to confirm that when I disabled Gmusic I am able to run the m3u backend again.  I haven't uninstalled the future package. 

Regards

C

**Comment by adamcik** [comment] 2016-08-23 21:07
Sounds like something that should be raised as a bug against future. That they break code that uses intern, but doesn't itself use future is kinda bad.

**Comment by tkem** [comment] 2016-08-24 06:02
@adamcik: Well, I still haven't figured out what's really going on here, so I think it's too early to blame any party apparently involved ;-)
Still, making field interning Py3-ready might be a good idea anyway, and would probably work around this issue. Further analysis has to wait until the weekend, though.

**Comment by tkem** [comment] 2016-09-01 14:41
I was now able to reproduce this on Debian Jessie x86, so it's not limited to Raspbian, at least.
Only difference so far I can see is the Python version, which is 2.7.9 on Debian/Raspbian Jessie, and 2.7.12 on Ubuntu 16.04.

**Comment by tkem** [comment] 2016-09-02 07:41
Update: It looks like `gmusicapi` makes use of `future`'s "standard library aliases" quite a lot:
```
from future import standard_library
standard_library.install_aliases()
```
Among other things, this means that `future` will install a backported `urllib.parse` which uses its own incompatible string types. In a (maybe misguided) attempt for Python 3 compatibility,  `mopidy.m3u.translator` picks these up:
```
try:
    from urllib.parse import quote_from_bytes, unquote_to_bytes
except ImportError:
    # "normal" Python 2 path
```
and therefore gets to use `future.types.newstr.newstr` as its URI type, which can't be `intern`ed.

**Comment by tkem** [comment] 2016-09-02 12:09
I was finally able to reproduce the error also on Ubuntu 16.04, at last, by adding an 
```
import gmusicapi
```
directly in `mopidy/m3u/translator.py`.

My current guess (and so far, these are all "guesses" and not "blames" or whatever) is therefore that this simply a matter of import order, which may differ for platforms and may also be subject to race conditions (i.e. when extensions are created/started).

**Comment by tkem** [comment] 2016-09-03 11:25
@adamcik :The nice people over at https://github.com/simon-weber/gmusicapi did just that:

https://github.com/PythonCharmers/python-future/issues/236

**Comment by adamcik** [comment] 2016-10-02 11:57
Closing this on our end as we can do anything but wait for upstream to fix it.

**Closed by adamcik** 2016-10-02 11:57 UTC

**Comment by adamcik** [comment] 2016-10-02 11:59
Alternatively we drop using `intern` and the models memory usage goes up again.
