### ISSUE TITLE
Allow multiple backends use same URI schemes

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#908] opened 2014-12-14 14:39 UTC
This would be very nice for allowing backends to claim http links that correspond to things they know how to play. Exact mechanism we should use for this is still a bit uncertain be it just ask all of them and use the answer from the one that claims it, have some "routing" system or some other means of handling this.

We at least need a way to handle multiple backends such as the generic stream backend and a more specific one trying to handle the same urls.

**Comment by jodal** [comment] 2015-03-18 19:44
This looks like a duplicate of #696.

**Closed by jodal** 2015-03-18 19:44 UTC
Labels: Core, enhancement
