### ISSUE TITLE
Feature request: support switching between multiple outputs from within mopidy/mpd client

### ISSUE THREAD

**Issue by aanno** [mopidy/mopidy#1524] opened 2016-06-07 06:49 UTC
Feature request: support switching between multiple outputs from within mopidy/mpd client

Currently, mopidy supports multiple outputs by using the gst infrastructure (more details at https://discuss.mopidy.com/t/some-questions-on-mopidy/855). The problem with this approach however is that it is impossible _to switch between multiple outputs from within mopidy/mpd clients_ the way it is possible with the 'traditional' mpd.

Please support multiple output the way 'traditional' mpd does!

**Comment by kingosticks** [comment] 2016-06-07 09:41
This is a duplicate of https://github.com/mopidy/mopidy/issues/1118

**Closed by kingosticks** 2016-06-07 09:41 UTC
