### ISSUE TITLE
webstream output for inhouse webradio streaming like icecast:"Extension wishlist" 

### ISSUE THREAD

**Issue by fashionbye** [mopidy/mopidy#1200] opened 2015-06-16 13:24 UTC
webstream output for inhouse webradio streaming like icecast:"Extension wishlist"

**Comment by fashionbye** [comment] 2015-06-16 13:24
webstream output for inhouse webradio streaming like icecast:"Extension wishlist"

**Comment by jodal** [comment] 2015-06-25 21:58
I think I maybe see what you're aiming for, but it is not very clear, so please elaborate a bit on what you want.

**Comment by fashionbye** [comment] 2015-06-29 11:53
Dear jodal, multiroom solutions are very trendy. Some realize this via rtp-streaming (Logitech Squeezebox standard), others like me ínstall i.e. an icecast server which allows streaming to several clients (webradios) all over the house (with different channels to choose from incl. Bluetooth, Airplay functionality, several playlist channels and one Volumio channel. webatreaming via LAN cable is really synchronous (only on identical devices). Disadvantage depending on settings approx. 2 seconds time delay.
Some people often play around with any controlling device, others like to choose from several entertainment channels like on board of an aircraft and just let it play. In case of a party, Volumio is the choice! With its Airplay capability one can offer guests to play some songs via Airplay.
I had six Apple Airport Express spread across the house. With Volumio: zero, nil, all sold on ebay.
If you would integrate an icecast server or even MPD httpd output, this would be a great effort.
By the way, the Raspberry does not need ANY sound card device then, just a virtual one with loopback settings.
P.S. my webradios are radio controlled (not infrared) little boxes, called FS20IRB. Simple but perfect.

**Comment by adamcik** [comment] 2015-12-05 21:58
Closing as dupe of https://github.com/mopidy/mopidy/issues/56

**Closed by adamcik** 2015-12-05 21:58 UTC
Labels: enhancement
