### ISSUE TITLE
Add an option to create a fifo instead of a file (via filesink)

### ISSUE THREAD

**Issue by tgurr** [mopidy/mopidy#1636] opened 2017-08-14 22:10 UTC
I was going to use the filesink output

```
[audio]
output = audioresample ! audio/x-raw,rate=48000,channels=2,format=S16LE ! audioconvert ! wavenc ! filesink location=/tmp/snapfifo
```

to be able to use mopidy in combination with snapcast and had the issue that the sound got repeated indefinitely after stopping the music in mopidy. It turned out the filesink plugin created a regular file instead of a fifo which I guess is more than normal. However it would be neat to have an option for mopidy to create a fifo instead, since it seems I wasn't the only person running into that kind of propblem:

https://github.com/badaix/snapcast/issues/96

Maybe we could have a "fifosink" additionally to the "filesink" to prevent such mistakes? Or an additional option to the filesink like e.g. `[...] ! filesink location=/tmp/snapfifo createmode=fifo`

**Comment by trygveaa** [comment] 2017-08-14 22:14
See #775.

**Comment by tgurr** [comment] 2017-08-14 22:21
Oh alright thanks, I saw that issue when doing a search and hat a look at it but I didn't really get that is indeed about the feature I'm asking for. However I've to say when manually creating the fifo and just using the already available normal filesink pointing it to that fifo it works pretty well for me. But for sure I'm no expert and that might be just a hacky solution until it is implemented properly. Feel free to close this issue as a duplicate then.

**Comment by trygveaa** [comment] 2017-08-17 00:29
Ah, alright. I don't know the details, or if there is any issues using fifo files so I'll let this stay open.

**Comment by axm2** [comment] 2017-10-08 02:36
I created the fifo manually but when I tell mpd to pause or stop the fifo gets messed up and mopidy crashes. I'm not sure if this is related to the fact that mopidy uses filesink or not.

**Comment by adamcik** [comment] 2019-11-27 19:45
Closing this as a duplicate of #775 which has a lot of the things needed figured out, it's just waiting for someone to package it all up.

**Closed by adamcik** 2019-11-27 19:45 UTC
Labels: A-audio, C-enhancement
