### ISSUE TITLE
event:optionsChanged does not include changes

### ISSUE THREAD

**Issue by morgoth** [mopidy/mopidy#1095] opened 2015-03-30 20:10 UTC
It would be nice to report changes on this event.
Currently when something changes and one want to have synchronized all options (random, repeat, consume) it has to request all the options again, because event doesn't say what was the change.
Other option would be to create unique event for each option.

**Comment by adamcik** [comment] 2015-03-30 20:14
Dupe of #977 :-)

**Closed by adamcik** 2015-03-30 20:14 UTC
