### ISSUE TITLE
Enhancement: Official Spotify Connect extension!

### ISSUE THREAD

**Issue by ibex-are-goats** [mopidy/mopidy#1922] opened 2020-07-05 20:00 UTC
Mopidy does everything I need except Spotify Connect, so I have to use Volumio. With an official MopidySpotifyConnect plugin, more people will be able to migrate to purely using Mopidy!

Please find some related projects below:
https://github.com/volumio/volumio-plugins/tree/master/plugins/music_service/volspotconnect2
https://github.com/librespot-org/librespot
https://github.com/Spotifyd/spotifyd
https://github.com/kodi-community-addons/plugin.audio.spotify
https://github.com/nicokaiser/rpi-audio-receiver

**Comment by kingosticks** [comment] 2020-07-05 20:08
This is a duplicate of https://github.com/mopidy/mopidy-spotify/issues/14

And yes, that issue is locked but there's nothing new to say. Spotify have still not released a library we can use and librespot is still not in a state we can use.

**Closed** 2020-07-05 20:08 UTC
Labels: C-extension-request

**Comment by ibex-are-goats** [comment] 2020-07-05 20:40
I don't know what you mean by "state you can use", but I'm using spotify connect with volumio every day!

**Comment by kingosticks** [comment] 2020-07-05 21:26
OK, well if you could integrate it into Mopidy-Spotify and open a PR there (not here) we'll review the merge.
