### ISSUE TITLE
Add albums to artist-lookup results

### ISSUE THREAD

**Issue by woutervanwijk** [mopidy/mopidy#324] opened 2013-01-16 11:04 UTC
For the webclient it would be nice if Mopidy returned albums and tracks when lookingup an artist, not only tracks. A bit like the search results now. It's a nice-to-have...

**Comment by jodal** [comment] 2018-03-31 22:02
Duplicate of #738. I'm keeping the newer issue and closing this one.

**Closed by jodal** 2018-03-31 22:02 UTC
Labels: A-core, C-enhancement
