### ISSUE TITLE
Simplify GStreamer based playlist handling.

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy#701] opened 2014-02-18 12:10 UTC
http://gstreamer.freedesktop.org/data/doc/gstreamer/0.10.36/gst-plugins-base-plugins/html/gst-plugins-base-plugins-playbin2.html

> Handling redirects
> 
> Some elements may post 'redirect' messages on the bus to tell the application to open another location. These are element messages containing a structure named 'redirect' along with a 'new-location' field of string type. The new location may be a relative or an absolute URI. Examples for such redirects can be found in many quicktime movie trailers.

So instead of crazy sub-decodebin and broken chains in the pipeline we can just redirect to one of the resolved URLs.

**Comment by adamcik** [comment] 2015-02-10 23:03
```
+kingosticks    Is the blocking playlist thing just to have the typefinders
                called by our (audio?) code first, rather than linked into gstreamer's pipe?
+kingosticks    and have our own code that peeks into the files etc
+adamcik        the flow should be 1) create source from the uri 2) connect
                that src to a typefinder 3) connect the typefinder to a
                decodebin2 4) connect a callback to the typefinder 5) abort the
                pipeline if the callback finds text/* or something like that
+adamcik        then from there the next step is simply to urlopen the uri and
                try and do the plparsing
+adamcik        I was looking at having the scanner download the pl, but that
                is just making things complex
+adamcik        so better to just give up and do it outside - also works better
                with do one thing well type thinking :-)
+kingosticks    indeed ok
+adamcik        and it's better for totem plparser in the future :-)
+adamcik        this should probably be in some bug and not just in irc logs...
+adamcik        of course after this is done there would be the cleanup of
                removing the playlist elements etc
+jodal          given that this is the last blocker for pygi/gst1/python3, yes,
                this really should go in a bug, and be pinned to the top of every bug view :-)
```

**Comment by jodal** [comment] 2015-09-02 00:42
Duplicate of #671.

**Closed by jodal** 2015-09-02 00:42 UTC
Labels: 1 - Ready, Audio, enhancement
