### ISSUE TITLE
WARNING  Element doesn't implement handling of this stream. Please file a bug.

### ISSUE THREAD

**Issue by machacd** [mopidy/mopidy#1211] opened 2015-07-05 09:33 UTC
```
WARNING  Element doesn't implement handling of this stream. Please file a bug.
```

I suddenly get this warning message when I try to play a track from spotify. The progressbar keeps moving, but no sound. I'm using Archlinux on RaspberryPi.

**Comment by jodal** [comment] 2015-07-05 17:33
How did you install Mopidy? Or, in other words, how did you get GStreamer installed, and what plugins to GStreamer was included?

Do you know what stream/file you where playing when this happened?

**Comment by machacd** [comment] 2015-07-05 21:12
I have installed everything through the arch repositories, including GStreamer0.1. I have the base, good, ugly, bad packages plus their respective plugins. Then ffmepg and python gstreamer plugins.

The stream played was spotify, but now I see, that the youtube stream has the same issue.

**Comment by jodal** [comment] 2015-07-05 21:16
That error shouldn't be possible with Spotify playback, as we give GStreamer raw PCM audio from libspotify, and there's nothing to decode for GStreamer.

Can you provide a debug log where you reproduce this, maybe also including GStreamer debug information? Relevant resources are:

https://docs.mopidy.com/en/latest/troubleshooting/#debug-logging
https://docs.mopidy.com/en/latest/troubleshooting/#debugging-gstreamer

**Comment by machacd** [comment] 2015-07-08 10:06
This is the ouptut of mopidy debug at the relevant spot:
```
  Triggering track playback started event
DEBUG    2015-07-08 09:50:54,352 [5260:MainThread] mopidy.listener
  Sending track_playback_started to CoreListener: {'tl_track': TlTrack(tlid=18, track=Track(album=Album(artists=[Artist(name=u'Beastie Boys', uri=u'spotify:artist:03r4iKL2g2442PT9n2UKsx')], date=u'1994', name=u'Ill Communication', uri=u'spotify:album:6lfjbwFGzQ6aSNP1N3JlT8'), artists=[Artist(name=u'Beastie Boys', uri=u'spotify:artist:03r4iKL2g2442PT9n2UKsx')], bitrate=320, date=u'1994', length=188000, name=u'Bodhisattva Vow', track_no=19, uri=u'spotify:track:0UaaJFIosWfcGxeArRxDMV'))}
DEBUG    2015-07-08 09:50:54,347 [5260:SpotifyBackend-8] mopidy_spotify.playback
  playback.on_need_data(0) called
DEBUG    2015-07-08 09:50:54,599 [5260:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.0.17: u'{"method":"core.tracklist.get_tracks","jsonrpc":"2.0","id":76}'
DEBUG    2015-07-08 09:50:54,638 [5260:SpotifyBackend-8] mopidy_spotify.playback
  playback.on_need_data(0) called
DEBUG    2015-07-08 09:50:55,134 [5260:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.0.17: u'{"method":"core.playback.get_current_track","jsonrpc":"2.0","id":77}'
DEBUG    2015-07-08 09:50:55,187 [5260:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.0.17: u'{"method":"core.playback.get_current_track","jsonrpc":"2.0","id":78}'
DEBUG    2015-07-08 09:50:55,252 [5260:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.0.17: u'{"method":"core.playback.get_time_position","jsonrpc":"2.0","id":79}'
DEBUG    2015-07-08 09:50:55,289 [5260:Audio-2] mopidy.audio.actor
  Position query failed
DEBUG    2015-07-08 09:50:55,326 [5260:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.0.17: u'{"method":"core.playback.get_current_track","jsonrpc":"2.0","id":80}'
WARNING  2015-07-08 09:50:55,381 [5260:MainThread] mopidy.audio.gst
  Element doesn't implement handling of this stream. Please file a bug.
DEBUG    2015-07-08 09:50:55,385 [5260:MainThread] mopidy.audio.gst
  gstplaysink.c(2718): gen_audio_chain (): /GstPlayBin2:playbin20/GstPlaySink:playsink:
Volume/mute is not available
DEBUG    2015-07-08 09:50:55,392 [5260:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.0.17: u'{"method":"core.playback.get_time_position","jsonrpc":"2.0","id":81}'
DEBUG    2015-07-08 09:50:55,428 [5260:Audio-2] mopidy.audio.actor
  Position query failed
DEBUG    2015-07-08 09:50:55,494 [5260:HttpServer] mopidy.http.handlers
  Received WebSocket message from 192.168.0.17: u'{"method":"core.playback.get_time_position","jsonrpc":"2.0","id":82}'
DEBUG    2015-07-08 09:50:55,539 [5260:SpotifyBackend-8] mopidy_spotify.playback
  playback.on_need_data(0) called
DEBUG    2015-07-08 09:50:55,596 [5260:SpotifyBackend-8] mopidy_spotify.playback
  playback.on_need_data(0) called
DEBUG    2015-07-08 09:50:55,630 [5260:SpotifyBackend-8] mopidy_spotify.playback
```

I cannot debug gstreamer, if I follow the guide that you've mentioned, I get
```
Exception in thread SpotifyThread (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/site-packages/mopidy/utils/process.py", line 73, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'debug'
```

**Comment by jodal** [comment] 2015-07-08 10:15
That exception is probably just from a race condition during interpreter shutdown where the logging object is gone before the SpotifyThread is shut down, and thus it fails logging that it is shutting down.

I tried out the GStreamer debugging guide, and the following command works and produces two log files, `mopidy.log` and `gstreamer.log`:

```
GST_DEBUG=3 GST_DEBUG_FILE=gstreamer.log mopidy --save-debug-log
```

**Comment by machacd** [comment] 2015-07-08 10:27
Ok, I see, thanks. Now I was able to produce gstreamer log too:
https://dl.dropboxusercontent.com/u/23101549/gstreamer.log
I just played a track and paused it quickly.

**Comment by jodal** [comment] 2015-07-08 10:49
@adamcik Do you have time to have a look at this?

**Comment by adamcik** [comment] 2015-07-22 12:03
Hmm, your log doesn't have the `Element doesn't implement handling of this stream. Please file a bug.` line. So don't think I can figure out what went wrong here.

Also this is an error message from GStreamer, so it would need to be a bug there. However since we are on 0.10 which isn't supported anymore it would just get closed with won't fix. So I have no idea, and don't think we can actually fix this in mopidy at least :(

**Closed by adamcik** 2015-07-22 12:03 UTC
Labels: Audio, bug
