### ISSUE TITLE
Music queue (playlist) not preserved across mopidy restarts / computer reboots

### ISSUE THREAD

**Issue by tb01110100** [mopidy/mopidy#1201] opened 2015-06-18 19:50 UTC
Title says it all. Is this intentional or maybe there's a setting I'm missing?

**Comment by adamcik** [comment] 2015-06-19 08:07
This is a dupe of #310 which hasn't made the top of anyone's priorities yet, contributions would be welcome. The last couple of comments should give a clear idea of the suggested implementation.

**Closed by adamcik** 2015-06-19 08:07 UTC
