### ISSUE TITLE
most of the mp3 not scanned

### ISSUE THREAD

**Issue by r100gs** [mopidy/mopidy#1480] opened 2016-03-08 12:05 UTC
Hello guyes,

I am running mopidy since 2 years! Great work so far. THX!!

The problem is, that it doesnt scan most of my mp3 songs anymore! The failure is

Track shorter than 100ms

e. g.:
WARNING  Failed local:track:vdr/Elvis%20Presley/The%20Other%20Side%20Hits%20Vol.2/%23%20THE%20OTHER%20SIDES%20HITS%20VOL.2%20-06-%20I%20Believe%20In%20The%20Man.mp3: Track shorter than 100ms

With the old mopidy version before 2.0 and gstreamer0.1 everything was fine.
What can I do? 

Best regards,
Stefan

**Comment by kingosticks** [comment] 2016-03-08 12:19
Hi. This is a duplicate of https://github.com/mopidy/mopidy/issues/1474 and the more recent parts of https://github.com/mopidy/mopidy/issues/935

**Closed by kingosticks** 2016-03-08 12:19 UTC

**Comment by SeeSpotRun** [comment] 2016-03-19 08:07
@r100gs: if you have a chance, could you please test using https://github.com/SeeSpotRun/mopidy/tree/fix/gstreamer_not_pushing_tags_2 to see if this fixes the problem?  This branch has a workaround in mopidy/audio/scan.py to address an upstream bug in gstreamer.

Alternatively if you are feeling adventurous you could try compiling gstreamer from git source...

**Comment by jodal** [comment] 2016-08-07 07:15
Fixed by PR #1481.
