### ISSUE TITLE
Mopidy File backend doesnt work on Fedora 35 (with Python 3.10)

### ISSUE THREAD

**Issue by holdenSK** [mopidy/mopidy#2027] opened 2021-11-19 14:04 UTC
If you are not sure about anything below then please post on our [forum](https://discourse.mopidy.com/) first.

**Describe the bug**
Mopidy File backend doesn't work on Fedora 35 (with Python 3.10) anf dollowing error message is shown:

```
DEBUG    2021-11-19 09:55:11,815 [12275:Audio-2 (_actor_loop)] mopidy.audio.gst
  Got source-setup signal: element=GstFileSrc

(mopidy:12275): GStreamer-CRITICAL **: 09:55:11.815: gst_element_query: assertion 'GST_IS_ELEMENT (element)' failed

(mopidy:12275): GStreamer-CRITICAL **: 09:55:11.815: gst_bin_add: assertion 'GST_IS_ELEMENT (element)' failed
WARNING  2021-11-19 09:55:11,817 [12275:Audio-2 (_actor_loop)] py.warnings
  /home/lfurman/mopidy-dev/mopidy/mopidy/audio/actor.py:798: Warning: g_value_set_object: assertion 'G_IS_OBJECT (v_object)' failed
  result = self._playbin.set_state(state)

WARNING  2021-11-19 09:55:11,817 [12275:Audio-2 (_actor_loop)] py.warnings
  /home/lfurman/mopidy-dev/mopidy/mopidy/audio/actor.py:798: Warning: g_object_class_find_property: assertion 'G_IS_OBJECT_CLASS (class)' failed
  result = self._playbin.set_state(state)


(mopidy:12275): GStreamer-CRITICAL **: 09:55:11.817: gst_element_iterate_src_pads: assertion 'GST_IS_ELEMENT (element)' failed

(mopidy:12275): GStreamer-CRITICAL **: 09:55:11.817: gst_iterator_next: assertion 'it != NULL' failed

(mopidy:12275): GStreamer-CRITICAL **: 09:55:11.817: gst_iterator_free: assertion 'it != NULL' failed

(mopidy:12275): GStreamer-CRITICAL **: 09:55:11.817: gst_element_class_get_pad_template_list: assertion 'GST_IS_ELEMENT_CLASS (element_class)' failed
0:00:29.760731236 12275 0x7fa03402b860 WARN            uridecodebin gsturidecodebin.c:2343:setup_source:<uridecodebin0> error: Source element is invalid.
ERROR    2021-11-19 09:55:11,818 [12275:MainThread] mopidy.audio.gst
  GStreamer error: Source element is invalid.
DEBUG    2021-11-19 09:55:11,818 [12275:MainThread] mopidy.audio.gst
  Got ERROR bus message: error=GLib.Error('Source element is invalid.', 'gst-core-error-quark', 1) debug='../gst/playback/gsturidecodebin.c(2343): setup_source (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0'

(mopidy:12275): GStreamer-CRITICAL **: 09:55:11.818: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed

(mopidy:12275): GStreamer-CRITICAL **: 09:55:11.818: gst_bin_remove: assertion 'GST_IS_ELEMENT (element)' failed
DEBUG    2021-11-19 09:55:11,818 [12275:Audio-2 (_actor_loop)] mopidy.audio.gst
  Changing state to GST_STATE_PLAYING: result=GST_STATE_CHANGE_FAILURE
DEBUG    2021-11-19 09:55:11,818 [12275:MainThread] mopidy.audio.gst
  Changing state to GST_STATE_NULL: result=GST_STATE_CHANGE_SUCCESS
WARNING  2021-11-19 09:55:11,818 [12275:Audio-2 (_actor_loop)] mopidy.audio.actor
  Setting GStreamer state to GST_STATE_PLAYING failed
WARNING  2021-11-19 09:55:11,819 [12275:Core-6 (_actor_loop)] mopidy.core.tracklist
  Track is not playable: file:///home/lfurman/Music/Fun/saral.mp3
DEBUG    2021-11-19 09:55:11,819 [12275:Core-6 (_actor_loop)] mopidy.listener
```
Same error occurs when using Mopidy-Local extension, so this might be related to some core functionality.

**How to reproduce**
Play local track on fedora 35 with mopidy (even with stock config); same error occurs wteh running tests on devel branch according to https://docs.mopidy.com/en/latest/devenv/#test-it-all and adding py310 as test target.

**Expected behaviour**
Local files playback works as usual.

**Environment**

- Operating system: Fedora 35 Workstation with latest updates
- [Running Mopidy](https://docs.mopidy.com/en/latest/running/) as a service or in the terminal? In terminal or as user service via `systemd`.
- Your config (output of `sudo mopidyctl config`):
```
[core]
cache_dir = $XDG_CACHE_DIR/mopidy
config_dir = $XDG_CONFIG_DIR/mopidy
data_dir = $XDG_DATA_DIR/mopidy
max_tracklist_length = 10000
restore_state = true

[logging]
verbosity = 0
format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
color = true
config_file =

[audio]
mixer = software
mixer_volume = 33
output = autoaudiosink
buffer_time = 

[proxy]
scheme = 
hostname = 
port = 
username = 
password = 

[spotify]
enabled = true
username = ****************
password = ********
client_id = **************************
client_secret = ********
bitrate = 320
volume_normalization = true
private_session = false
timeout = 10
allow_cache = true
allow_network = true
allow_playlists = true
search_album_count = 20
search_artist_count = 10
search_track_count = 50
toplist_countries = 
  Slovakia

[mpris]
enabled = true
bus_type = session

[file]
enabled = true
media_dirs = 
  $XDG_MUSIC_DIR|Music
  ~/|Home
excluded_file_extensions = 
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000

[http]
enabled = true
hostname = 127.0.0.1
port = 6680
zeroconf = Mopidy HTTP server on $hostname
allowed_origins = 
csrf_protection = true
default_app = mopidy

[m3u]
enabled = true
base_dir = $XDG_MUSIC_DIR
default_encoding = latin-1
default_extension = .m3u8
playlists_dir =

[softwaremixer]
enabled = true

[stream]
enabled = true
protocols = 
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist = 
timeout = 5000

[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600
password = 
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname
command_blacklist = 
  listall
  listallinfo
default_playlist_scheme = m3u
```
- Software versions (output of `sudo mopidyctl deps`)
```
Executable: /usr/bin/mopidy
Platform: Linux-5.14.18-300.fc35.x86_64-x86_64-with-glibc2.34
Python: CPython 3.10.0 from /usr/lib64/python3.10
Mopidy: 3.2.0 from /usr/lib/python3.10/site-packages
  Pykka: 2.0.2 from /usr/lib/python3.10/site-packages
  requests: 2.26.0 from /usr/lib/python3.10/site-packages
    charset-normalizer: 2.0.4 from /usr/lib/python3.10/site-packages
    idna: 3.2 from /usr/lib/python3.10/site-packages
    urllib3: 1.26.6 from /usr/lib/python3.10/site-packages
  setuptools: 57.4.0 from /usr/lib/python3.10/site-packages
  tornado: 6.1 from /usr/lib64/python3.10/site-packages
Mopidy-Spotify: 4.1.1 from /home/lfurman/.local/lib/python3.10/site-packages
  pyspotify: 2.1.3 from /home/lfurman/.local/lib/python3.10/site-packages
    cffi: 1.14.6 from /usr/lib64/python3.10/site-packages
      pycparser: 2.20 from /usr/lib/python3.10/site-packages
        ply: 3.11 from /usr/lib/python3.10/site-packages
    setuptools: 57.4.0 from /usr/lib/python3.10/site-packages
  requests: 2.26.0 from /usr/lib/python3.10/site-packages
    charset-normalizer: 2.0.4 from /usr/lib/python3.10/site-packages
    idna: 3.2 from /usr/lib/python3.10/site-packages
    urllib3: 1.26.6 from /usr/lib/python3.10/site-packages
  setuptools: 57.4.0 from /usr/lib/python3.10/site-packages
  Pykka: 2.0.2 from /usr/lib/python3.10/site-packages
  Mopidy: 3.2.0 from /usr/lib/python3.10/site-packages
Mopidy-MPRIS: 3.0.3 from /home/lfurman/.local/lib/python3.10/site-packages
  Mopidy: 3.2.0 from /usr/lib/python3.10/site-packages
  pydbus: 0.6.0 from /usr/lib/python3.10/site-packages
  setuptools: 57.4.0 from /usr/lib/python3.10/site-packages
  Pykka: 2.0.2 from /usr/lib/python3.10/site-packages
Mopidy-MPD: 3.2.0 from /usr/lib/python3.10/site-packages
  Mopidy: 3.2.0 from /usr/lib/python3.10/site-packages
  Pykka: 2.0.2 from /usr/lib/python3.10/site-packages
  setuptools: 57.4.0 from /usr/lib/python3.10/site-packages
GStreamer: 1.19.3.0 from /usr/lib64/python3.10/site-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.42.0
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
        mad
```
- Any specific hardware (e.g. an exotic USB soundcard): N/A

**Additional context**
Add any other context about the problem here. If appropriate, upload an [appropriately verbose](https://docs.mopidy.com/en/latest/troubleshooting/#debug-logging) log file showing the bug.

**Comment by ladislavfurman** [comment] 2021-12-17 07:45
Opened also bug report in Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2033542

**Comment by ladislavfurman** [comment] 2022-01-19 16:12
[Here](https://gist.github.com/ladislavfurman/f1d1b69b9720fd85e01c6a8db19296f4) is tox tests running on `develop` branch on Fedora 35 with Python 3.10

**Comment by kingosticks** [comment] 2022-01-19 16:56
And probably crucially, GStreamer 1.19.3. I don't have cycles to debug compatibility with unstable GST releases but perhaps it is related to https://gitlab.freedesktop.org/gstreamer/gstreamer/-/blob/main/subprojects/gst-devtools/NEWS#L279

**Comment by holdenSK** [comment] 2022-01-21 14:34
I tested also on current develop branch: when I comment out https://github.com/mopidy/mopidy/blob/796ebe9b4e1fe7efdb24199cda810492dcb903a1/mopidy/audio/actor.py#L487, File backend works but Spotify conversely stops.

**Comment by kingosticks** [comment] 2022-01-21 15:06
`_on_source_setup` is important for Spotify playback as that is where we engage/disengage the Spotify appsrc element. OK, well as least that experiment confirms the breaking GST change is the issue.

**Comment by kingosticks** [comment] 2022-01-21 15:33
Want to try just commenting out bits and see what is doesn't like? Is it `source.get_factory().get_name()` ??! Also be good to understand are you trying to play a mix of Spotify and File tracks ? It's hard to understand what could be going wrong for non-Spotify playback due to calling `_on_source_setup` early - it doesn't do much...

**Comment by holdenSK** [comment] 2022-01-21 16:25
Yes - I test on playlist with both spotify and non-spotify tracks although I also tested on playlist with just one  local track, it failed  there as well. I tried commenting out  some or al lines in `_on_source_setup` but if failed as well.

**Comment by girst** [comment] 2022-02-22 18:04
Fedora 35 has updated to gstreamer 0.20 a few weeks ago, and I can't reproduce this bug any more.

**Comment by girst** [comment] 2022-11-29 19:21
This Fedora bug was fixed in February. Moreover, fc35 will be obsolete in two weeks.

**Closed by girst** 2022-11-29 19:21 UTC
